[package]
name = "vulkan-tutorial-rs"
version = "0.1.0"
authors = ["Valentin Ignatev <valentignatev@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ash = "0.33.1"
winit = "0.20.0-alpha3"
